[tool.poetry]
name = "deeprl"
version = "0.1.0"
description = ""
authors = ["Mattia2700 <mattia2700f+dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
